// Generated by https://quicktype.io

export type Categories = Category[];

export interface Category {
    _id:       string;
    name:      string;
    isActive:  boolean;
    icon:      string;
    createdAt: string;
    updatedAt: string;
    __v:       number;
}

export interface Product {
    reviews:      any[];
    _id:          string;
    name:         string;
    price:        string;
    size:         Size;
    description:  string;
    details:      string;
    image:        string;
    images:       string[];
    isFeatured:   string;
    isActive:     boolean;
    category:     Category;
    countInStock: number;
    ratings:      number;
    discount:     string;
    createdAt:    string;
    updatedAt:    string;
    __v:          number;
}


export enum Size {
    Large = "large",
    Medium = "medium",
}


// Generated by https://quicktype.io

export interface UserResponse {
    user:          User;
    access_token:  string;
    refresh_token: string;
}

export interface User {
    _id:      string;
    avatar:   string;
    name:     string;
    email:    string;
    phone:    string;
    password: string;
    address:  Address[];
    role:     string;
    wishlist: string[];
    orders:   string[];
    access_token:  string;
    refresh_token: string;
}

export interface Address {
    _id:                   string;
    address_type:          string;
    country:               string;
    state_province_region: string;
    city_town:             string;
    zip_postal_code:       string;
    street:                string;
    landmark:              string;
    secondary_contact:     number;
    createdAt:             string;
    updatedAt:             string;
    __v:                   number;
}
