// Generated by https://quicktype.io

export type Categories = Category[];

export interface Category {
    _id:       string;
    name:      string;
    isActive:  boolean;
    icon:      string;
    createdAt: string;
    updatedAt: string;
    __v:       number;
}
